# Generated by Django 5.2.7 on 2026-03-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('origin_keywords', models.CharField(blank=True, help_text='Ciudades/países de origen separados por coma', max_length=500)),
                ('destination_keywords', models.CharField(blank=True, help_text='Ciudades/países de destino separados por coma', max_length=500)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('max_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aircraft_categories', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(choices=[('immediate', 'Inmediata'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción de Alerta',
                'verbose_name_plural': 'Suscripciones de Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('was_read', models.BooleanField(default=False)),
                ('empty_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='flights.emptyleg')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.alertsubscription')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-sent_at'],
                'unique_together': {('subscription', 'empty_leg')},
            },
        ),
    ]
