# Generated by Django 5.2.7 on 2026-03-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('light', 'Light Jet'), ('midsize', 'Midsize Jet'), ('super_midsize', 'Super Midsize Jet'), ('heavy', 'Heavy Jet'), ('ultra_long', 'Ultra Long Range'), ('turboprop', 'Turboprop'), ('helicopter', 'Helicóptero'), ('other', 'Otro')], default='other', max_length=20)),
                ('max_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('cruise_speed_kmh', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(db_index=True, max_length=4, unique=True)),
                ('iata', models.CharField(blank=True, db_index=True, max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['icao'],
            },
        ),
        migrations.CreateModel(
            name='FlightSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('web_public', 'Web Pública'), ('web_private', 'Web Privada'), ('api', 'API'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], default='web_public', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scrape_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('requires_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Datos',
                'verbose_name_plural': 'Fuentes de Datos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('company_type', models.CharField(choices=[('operator', 'Operador'), ('broker', 'Broker')], default='operator', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('callsign', models.CharField(blank=True, max_length=20)),
                ('registration', models.CharField(blank=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('origin_raw', models.CharField(blank=True, max_length=200)),
                ('destination_raw', models.CharField(blank=True, max_length=200)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('aircraft_raw', models.CharField(blank=True, max_length=200)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('en_route', 'En Ruta'), ('landed', 'Aterrizado'), ('cancelled', 'Cancelado'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.aircraft')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='flights.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.flightsource')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='EmptyLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('origin_raw', models.CharField(blank=True, max_length=200)),
                ('destination_raw', models.CharField(blank=True, max_length=200)),
                ('departure_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('flexible_dates', models.BooleanField(default=False)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('aircraft_raw', models.CharField(blank=True, max_length=200)),
                ('max_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Reservado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='available', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.aircraft')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_leg_arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_leg_departures', to='flights.airport')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_legs', to='flights.flight')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empty_legs', to='flights.flightsource')),
                ('operator_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_legs', to='flights.operator')),
            ],
            options={
                'verbose_name': 'Empty Leg',
                'verbose_name_plural': 'Empty Legs',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('closed', 'Cerrado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empty_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='flights.emptyleg')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flightsource',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='flights.operator'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_flight_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='emptyleg',
            index=models.Index(fields=['departure_date', 'status'], name='flights_emp_departu_071f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='emptyleg',
            index=models.Index(fields=['source', 'external_id'], name='flights_emp_source__039db0_idx'),
        ),
        migrations.AddIndex(
            model_name='emptyleg',
            index=models.Index(fields=['published', 'status', 'departure_date'], name='flights_emp_publish_b8d164_idx'),
        ),
    ]
